apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-provisioner-scaler
  namespace: transcoder
spec:
  scaleTargetRef:
    name: provisioner-worker
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      queueName: keda-provision
      queueLength: "1"
      host: RabbitMQHost
